///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Task_TA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case4_v2 recording.
    /// </summary>
    [TestModule("475f5784-16af-40f7-a2a9-6596a97ccc80", ModuleType.Recording, 1)]
    public partial class Case4_v2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Task_TARepository repository.
        /// </summary>
        public static Task_TARepository repo = Task_TARepository.Instance;

        static Case4_v2 instance = new Case4_v2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case4_v2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case4_v2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.None8' at 11;23.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.None8Info, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.None8.Click("11;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.None9' at -334;336.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.None9Info, new RecordItemIndex(1));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.None9.Click("-334;336");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'testotomasyon{NumPad2}{NumPad2}{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}gmail.com' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.SelfInfo, new RecordItemIndex(2));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Self.EnsureVisible();
            Keyboard.Press("testotomasyon{NumPad2}{NumPad2}{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text' at 106;18.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.TextInfo, new RecordItemIndex(3));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text.Click("106;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'deneme{NumPad1}{NumPad2}.' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.TextInfo, new RecordItemIndex(4));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text.PressKeys("deneme{NumPad1}{NumPad2}.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.GİRİŞYAP' at 163;29.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.GİRİŞYAPInfo, new RecordItemIndex(5));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.GİRİŞYAP.Click("163;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayı' at 202;25.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayıInfo, new RecordItemIndex(6));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayı.Click("202;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'kulaklık' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayı'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayıInfo, new RecordItemIndex(7));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayı.PressKeys("kulaklık");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayı1' at 580;18.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayı1Info, new RecordItemIndex(8));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayı1.Click("580;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SepeteEkle1' at 31;3.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SepeteEkle1Info, new RecordItemIndex(9));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SepeteEkle1.Click("31;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SepeteEkle1' at 47;1.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SepeteEkle1Info, new RecordItemIndex(10));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SepeteEkle1.Click("47;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Sepetim' at 2;14.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SepetimInfo, new RecordItemIndex(11));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Sepetim.Click("2;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Sepetim2UEruen1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Sepetim2UEruen1Info, new RecordItemIndex(12));
            Validate.Exists(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Sepetim2UEruen1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text2'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text2Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text2Info, "Text", "2");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
