///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Task_TA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case3 recording.
    /// </summary>
    [TestModule("b3c976ca-a052-43de-bfb5-5d700c226a24", ModuleType.Recording, 1)]
    public partial class Case3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Task_TARepository repository.
        /// </summary>
        public static Task_TARepository repo = Task_TARepository.Instance;

        static Case3 instance = new Case3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case3()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case3 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.GirişYap' at 9;4.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.GirişYapInfo, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.GirişYap.Click("9;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.UEyeOl' at 150;18.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.UEyeOlInfo, new RecordItemIndex(1));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.UEyeOl.Click("150;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBox' at 186;13.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBoxInfo, new RecordItemIndex(2));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBox.Click("186;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '  e{NumPad1}{NumPad8}{NumPad0}{NumPad5}{NumPad0}{NumPad4}{NumPad0}{NumPad0}{NumPad8}' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBox'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBoxInfo, new RecordItemIndex(3));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBox.PressKeys("  e{NumPad1}{NumPad8}{NumPad0}{NumPad5}{NumPad0}{NumPad4}{NumPad0}{NumPad0}{NumPad8}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RMenu down}{LControlKey down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}stud.tau.edu.tr' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBox'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBoxInfo, new RecordItemIndex(4));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBox.PressKeys("{RMenu down}{LControlKey down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}stud.tau.edu.tr");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.TextE180504008AtstudTauEduTr' at 131;106.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.TextE180504008AtstudTauEduTrInfo, new RecordItemIndex(5));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.TextE180504008AtstudTauEduTr.Click("131;106");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'denme{NumPad1}{NumPad2}.' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.SelfInfo, new RecordItemIndex(6));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Self.EnsureVisible();
            Keyboard.Press("denme{NumPad1}{NumPad2}.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.None2'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.None2Info, new RecordItemIndex(7));
            Validate.Exists(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.None2Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.LuetfenGecerliBirEmailAdresiGiriniz'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.LuetfenGecerliBirEmailAdresiGirinizInfo, new RecordItemIndex(8));
            Validate.Exists(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.LuetfenGecerliBirEmailAdresiGirinizInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
