///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Task_TA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case4_v3 recording.
    /// </summary>
    [TestModule("53e22813-a293-4167-bdd1-0d3d0b9d56a4", ModuleType.Recording, 1)]
    public partial class Case4_v3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Task_TARepository repository.
        /// </summary>
        public static Task_TARepository repo = Task_TARepository.Instance;

        static Case4_v3 instance = new Case4_v3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case4_v3()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case4_v3 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SomeText' at 5;8.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SomeTextInfo, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SomeText.Click("5;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBox' at 111;16.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBoxInfo, new RecordItemIndex(1));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBox.Click("111;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'testotomasyon{NumPad2}{NumPad2}{RMenu down}{LControlKey down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}gmail.com' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBox'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBoxInfo, new RecordItemIndex(2));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.ComboBox.PressKeys("testotomasyon{NumPad2}{NumPad2}{RMenu down}{LControlKey down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text' at 103;11.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.TextInfo, new RecordItemIndex(3));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text.Click("103;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'deneme' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.TextInfo, new RecordItemIndex(4));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text.PressKeys("deneme");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad2}.' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.TextInfo, new RecordItemIndex(5));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text.PressKeys("{NumPad1}{NumPad2}.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.GİRİŞYAP' at 115;4.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.GİRİŞYAPInfo, new RecordItemIndex(6));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.GİRİŞYAP.Click("115;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayı' at 259;12.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayıInfo, new RecordItemIndex(7));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayı.Click("259;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'kulaklık' with focus on 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayı'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayıInfo, new RecordItemIndex(8));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.AradığınızUeruenKategoriVeyaMarkayı.PressKeys("kulaklık");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.KulaklıkKategori' at 58;7.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.KulaklıkKategoriInfo, new RecordItemIndex(9));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.KulaklıkKategori.Click("58;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SepeteEkleSepeteEklendi' at 154;6.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SepeteEkleSepeteEklendiInfo, new RecordItemIndex(10));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.SepeteEkleSepeteEklendi.Click("154;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Sepetim1' at 7;3.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Sepetim1Info, new RecordItemIndex(11));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Sepetim1.Click("7;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.PushButton' at 16;18.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.PushButtonInfo, new RecordItemIndex(12));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.PushButton.Click("16;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text2'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text2Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Text2Info, "Text", "2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Sepetim2UEruen1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Sepetim2UEruen1Info, new RecordItemIndex(14));
            Validate.Exists(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Sepetim2UEruen1Info);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
