///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Task_TA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Task_TARepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("94b6bcb2-24d6-4517-9c31-f2927da1e5ec")]
    public partial class Task_TARepository : RepoGenBaseFolder
    {
        static Task_TARepository instance = new Task_TARepository();
        Task_TARepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Task_TARepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder _entrendueruenlertuerkiyeninonlineal;

        /// <summary>
        /// Gets the singleton class instance representing the Task_TARepository element repository.
        /// </summary>
        [RepositoryFolder("94b6bcb2-24d6-4517-9c31-f2927da1e5ec")]
        public static Task_TARepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Task_TARepository() 
            : base("Task_TARepository", "/", null, 0, false, "94b6bcb2-24d6-4517-9c31-f2927da1e5ec", ".\\RepositoryImages\\Task_TARepository94b6bcb2.rximgres")
        {
            _applicationundertest = new Task_TARepositoryFolders.ApplicationUnderTestAppFolder(this);
            _entrendueruenlertuerkiyeninonlineal = new Task_TARepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("94b6bcb2-24d6-4517-9c31-f2927da1e5ec")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("848aea98-ff99-4f59-b818-25cacef0d364")]
        public virtual Task_TARepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAl folder.
        /// </summary>
        [RepositoryFolder("e0afeaca-d626-46a1-81b5-6b24e4a90768")]
        public virtual Task_TARepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder EnTrendUEruenlerTuerkiyeninOnlineAl
        {
            get { return _entrendueruenlertuerkiyeninonlineal; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Task_TARepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("848aea98-ff99-4f59-b818-25cacef0d364")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "848aea98-ff99-4f59-b818-25cacef0d364", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("848aea98-ff99-4f59-b818-25cacef0d364")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("848aea98-ff99-4f59-b818-25cacef0d364")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder folder.
        /// </summary>
        [RepositoryFolder("e0afeaca-d626-46a1-81b5-6b24e4a90768")]
        public partial class EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder : RepoGenBaseFolder
        {
            Task_TARepositoryFolders.GroupingFolder _grouping;
            RepoItemInfo _kapatInfo;

            /// <summary>
            /// Creates a new EnTrendUEruenlerTuerkiyeninOnlineAl  folder.
            /// </summary>
            public EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EnTrendUEruenlerTuerkiyeninOnlineAl", "/form[@title>'En Trend Ürünler Türkiye''nin']", parentFolder, 30000, null, true, "e0afeaca-d626-46a1-81b5-6b24e4a90768", "")
            {
                _grouping = new Task_TARepositoryFolders.GroupingFolder(this);
                _kapatInfo = new RepoItemInfo(this, "Kapat", "toolbar[@accessiblename='Tarayıcı sekmeleri']/button[@accessiblename='Kapat']", "toolbar[@accessiblename='Tarayıcı sekmeleri']/button[@accessiblename='Kapat']", 30000, null, "158c1ef4-ac65-46cf-8b69-0c2a4971fdb4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e0afeaca-d626-46a1-81b5-6b24e4a90768")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e0afeaca-d626-46a1-81b5-6b24e4a90768")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Kapat item.
            /// </summary>
            [RepositoryItem("158c1ef4-ac65-46cf-8b69-0c2a4971fdb4")]
            public virtual Ranorex.Button Kapat
            {
                get
                {
                    return _kapatInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Kapat item info.
            /// </summary>
            [RepositoryItemInfo("158c1ef4-ac65-46cf-8b69-0c2a4971fdb4")]
            public virtual RepoItemInfo KapatInfo
            {
                get
                {
                    return _kapatInfo;
                }
            }

            /// <summary>
            /// The Grouping folder.
            /// </summary>
            [RepositoryFolder("fff7e9de-1425-4e9b-8009-1f4ab08189b1")]
            public virtual Task_TARepositoryFolders.GroupingFolder Grouping
            {
                get { return _grouping; }
            }
        }

        /// <summary>
        /// The GroupingFolder folder.
        /// </summary>
        [RepositoryFolder("fff7e9de-1425-4e9b-8009-1f4ab08189b1")]
        public partial class GroupingFolder : RepoGenBaseFolder
        {
            RepoItemInfo _epostaInfo;
            RepoItemInfo _şifreInfo;
            RepoItemInfo _noneInfo;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _none1Info;
            RepoItemInfo _comboboxInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _ueyeol1Info;
            RepoItemInfo _combobox1Info;
            RepoItemInfo _none2Info;
            RepoItemInfo _none3Info;
            RepoItemInfo _none4Info;
            RepoItemInfo _ueyeol2Info;
            RepoItemInfo _texte180504008atatudtauedutrInfo;
            RepoItemInfo _none5Info;
            RepoItemInfo _text1Info;
            RepoItemInfo _luetfengecerlibiremailadresigirinizInfo;
            RepoItemInfo _texte180504008atstudtauedutrInfo;
            RepoItemInfo _gİrİşyapInfo;
            RepoItemInfo _aradığınızueruenkategoriveyamarkayıInfo;
            RepoItemInfo _none6Info;
            RepoItemInfo _none7Info;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _linksepetim2Info;
            RepoItemInfo _sepetim2ueruenInfo;
            RepoItemInfo _none8Info;
            RepoItemInfo _none9Info;
            RepoItemInfo _aradığınızueruenkategoriveyamarkayı1Info;
            RepoItemInfo _sepeteekle1Info;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _sepetim2ueruen1Info;
            RepoItemInfo _text2Info;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _kulaklıkkategoriInfo;
            RepoItemInfo _sepeteeklesepeteeklendiInfo;
            RepoItemInfo _sepetim1Info;
            RepoItemInfo _pushbuttonInfo;
            RepoItemInfo _aradığınızueruenkategoriveyamarkayı2Info;
            RepoItemInfo _none10Info;
            RepoItemInfo _none11Info;
            RepoItemInfo _linkfavorilerimInfo;
            RepoItemInfo _favorilerlistenizhenuezboşInfo;
            RepoItemInfo _cıkışyapInfo;
            RepoItemInfo _none12Info;

            /// <summary>
            /// Creates a new Grouping  folder.
            /// </summary>
            public GroupingFolder(RepoGenBaseFolder parentFolder) :
                    base("Grouping", "container[@accessiblerole='Grouping']", parentFolder, 30000, null, false, "fff7e9de-1425-4e9b-8009-1f4ab08189b1", "")
            {
                _epostaInfo = new RepoItemInfo(this, "EPosta", ".//container[@accessiblename='']/element[1]/element[3]/element[3]/element[1]/text[@accessiblename='E-Posta']/text[@accessiblename='E-Posta']", "text[@accessiblename='E-Posta' and @accessiblerole='Text']", 30000, null, "fb6d563c-056a-46f8-b546-3007e01fc71a");
                _şifreInfo = new RepoItemInfo(this, "Şifre", ".//container[@accessiblename='']/element[1]/element[3]/element[3]/element[2]/text[@accessiblename='Şifre']/text[@accessiblename='Şifre']", "text[@accessiblename='Şifre' and @accessiblerole='Text']", 30000, null, "cb34a144-8ae5-47c5-ba3e-d06bd9e5421d");
                _noneInfo = new RepoItemInfo(this, "None", ".//container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[3]/container[1]/?/?/link[@accessiblename='Kaçırma!']/element[@accessiblerole='None']", "link[@accessiblename='Kaçırma!']/element[@accessiblerole='None']", 30000, null, "162014f1-c456-4759-9200-d3df20733114");
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", "container[1]/?/?/container/element[1]/?/?/button[@accessiblename='Üye Ol']", "button[@accessiblename='Üye Ol']", 30000, null, "16635d52-2ab8-41b8-8263-c2ccf419cc71");
                _none1Info = new RepoItemInfo(this, "None1", "container[1]/?/?/container/element[1]/element[3]/element[3]/element[10]", "container[@accessiblename='']/element[1]/element[3]/element[3]/element[10]", 30000, null, "fa3be3e8-7c21-4a56-9cfa-6eec45b9add5");
                _comboboxInfo = new RepoItemInfo(this, "ComboBox", "container[1]/?/?/container/element[1]/element[3]/element[3]/element[1]/combobox[@accessiblerole='ComboBox']", "container[@accessiblename='']/element[1]/element[3]/element[3]/element[1]/combobox[@accessiblerole='ComboBox']", 30000, null, "7a1d5176-8a97-41e0-8157-a235275bd7f2");
                _textInfo = new RepoItemInfo(this, "Text", "container[1]/?/?/container/element[1]/element[3]/element[3]/element[2]/text[@accessiblerole='Text']", "container[@accessiblename='']/element[1]/element[3]/element[3]/element[2]/text[@accessiblerole='Text']", 30000, null, "7fb7e098-0622-4a4b-b0f3-6a9447920062");
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", "container[1]/?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element/element[@accessiblerole='None']/element[2]/element/element[1]/?/?/text[@accessiblename='Giriş Yap']", "container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[2]/element[@accessiblerole='None']/element[1]/element[3]/text[@accessiblename='Giriş Yap']", 30000, null, "91090ad5-2bc5-4dc4-a5b9-f30b03fe470e");
                _ueyeol1Info = new RepoItemInfo(this, "UEYEOL1", "container[1]/?/?/container/element[1]/element[3]/element[3]/button[@accessiblename='ÜYE OL']", "button[@accessiblename='ÜYE OL']", 30000, null, "25c5d3ef-6c04-45a1-bef2-d553c1523130");
                _combobox1Info = new RepoItemInfo(this, "ComboBox1", "container[1]/?/?/container/element[1]/element[3]/element[4]/element[1]/combobox[@accessiblerole='ComboBox']", "container[@accessiblename='']/element[1]/element[3]/element[4]/element[1]/combobox[@accessiblerole='ComboBox']", 30000, null, "6bfb9698-eeab-43c9-b88b-6318c424e96f");
                _none2Info = new RepoItemInfo(this, "None2", "container[1]/?/?/container/element[1]/element[3]/element[3]", "container[@accessiblename='']/element[1]/element[3]/element[3]", 30000, null, "260b5e68-f14c-4bb6-ab0b-f76fd035e4f0");
                _none3Info = new RepoItemInfo(this, "None3", "container[1]/?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element[@accessiblerole='None']/element[@accessiblerole='None']", "container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element[@accessiblerole='None']/element[@accessiblerole='None']", 30000, null, "534547dc-2426-4aae-a932-560ebda0b847");
                _none4Info = new RepoItemInfo(this, "None4", "container[1]/?/?/container/element[1]/element[3]/element[4]/element[10]", "container[@accessiblename='']/element[1]/element[3]/element[4]/element[10]", 30000, null, "66570af6-2cd4-43f8-bc25-4c9424e052dc");
                _ueyeol2Info = new RepoItemInfo(this, "UEYEOL2", "container[1]/?/?/container/element[1]/element[3]/element[4]/button[@accessiblename='ÜYE OL']", "button[@accessiblename='ÜYE OL']", 30000, null, "44cec552-b412-4b8e-a8be-5559ecfedd0b");
                _texte180504008atatudtauedutrInfo = new RepoItemInfo(this, "TextE180504008AtatudTauEduTr", ".//container[@accessiblename='']/element[1]/element[3]/element[3]/element[1]/combobox[@accessiblerole='ComboBox']/text[@accessiblename>' e180504008@atud.tau.edu.']", "text[@accessiblename>' e180504008@atud.tau.edu.']", 30000, null, "8e2a2e88-f857-4fd5-8e7a-ccd5487587c4");
                _none5Info = new RepoItemInfo(this, "None5", "container[1]/?/?/container/element[1]/element[3]/element[3]/element[4]", "container[@accessiblename='']/element[1]/element[3]/element[3]/element[4]", 30000, null, "9f0b9477-5519-467f-9db3-b1127cbb11de");
                _text1Info = new RepoItemInfo(this, "Text1", "container[1]/?/?/container/element[1]/element[3]/element[4]/element[2]/text[@accessiblerole='Text']", "container[@accessiblename='']/element[1]/element[3]/element[4]/element[2]/text[@accessiblerole='Text']", 30000, null, "0a134ab0-6a03-4cc9-ad39-a65813bdcdb0");
                _luetfengecerlibiremailadresigirinizInfo = new RepoItemInfo(this, "LuetfenGecerliBirEmailAdresiGiriniz", "container[1]/?/?/container/element[1]/element[3]/element[3]/?/?/text[@accessiblename>'Lütfen geçerli bir email adresi']", "text[@accessiblename>'Lütfen geçerli bir email adresi']", 30000, null, "5130c23e-674b-4f8c-900c-b6e70ab6f05f");
                _texte180504008atstudtauedutrInfo = new RepoItemInfo(this, "TextE180504008AtstudTauEduTr", ".//container[@accessiblename='']/element[1]/element[3]/element[3]/element[1]/combobox[@accessiblerole='ComboBox']/text[@accessiblename>'  e180504008@stud.tau.edu']", "text[@accessiblename>'  e180504008@stud.tau.edu']", 30000, null, "2dfcf164-ac26-429f-8b64-a250c08c0b2c");
                _gİrİşyapInfo = new RepoItemInfo(this, "GİRİŞYAP", "container[1]/?/?/container/element[1]/element[3]/element[3]/button[@accessiblename='GİRİŞ YAP']", "button[@accessiblename='GİRİŞ YAP']", 30000, null, "3c3019ef-f5d4-4394-a610-381907977ca5");
                _aradığınızueruenkategoriveyamarkayıInfo = new RepoItemInfo(this, "AradığınızUeruenKategoriVeyaMarkayı", "container[1]/?/?/container[@accessiblename>'Kadın Butikleri, Yeni Sezon']/element[1]/element[1]/element/element[@accessiblerole='None']/element[1]//text[@accessiblename>'Aradığınız ürün, kategori']", "text[@accessiblename>'Aradığınız ürün, kategori']", 30000, null, "15ff16fd-5706-41b2-813d-922b2939b735");
                _none6Info = new RepoItemInfo(this, "None6", "container[1]/?/?/container[@accessiblename>'Kadın Butikleri, Yeni Sezon']/element[1]/element[1]/element/element[@accessiblerole='None']/element[1]/element[@accessiblerole='None']/element[2]/element[@accessiblerole='None']", "container[@accessiblename>'Kadın Butikleri, Yeni Sezon']/element[1]/element[1]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[1]/element[@accessiblerole='None']/element[2]/element[@accessiblerole='None']", 30000, null, "085fa678-5b08-4e6b-a2ba-c061530a2c11");
                _none7Info = new RepoItemInfo(this, "None7", ".//container[@accessiblename>'kulaklık Modelleri, Fiyatları']/element[1]/element[3]/element[6]/button[@accessiblename>'Sepete Ekle Sepete Eklend']/element[1]", "button[@accessiblename>'Sepete Ekle Sepete Eklend']/element[1]", 30000, null, "f46e98cf-2457-4f18-bd4e-d16c560aebd1");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//container[@accessiblename>'kulaklık Modelleri, Fiyatları']/element[1]/element[3]/element[9]/button[@accessiblename>'Sepete Ekle Sepete Eklend']/?/?/text[@accessiblename='Sepete Ekle']", "container[@accessiblename>'kulaklık Modelleri, Fiyatları']/element[1]/element[3]/element[9]/button[@accessiblename>'Sepete Ekle Sepete Eklend']/element[1]/text[@accessiblename='Sepete Ekle']", 30000, null, "adc7d11e-3df4-4e74-b642-10d9cc800c08");
                _linksepetim2Info = new RepoItemInfo(this, "LinkSepetim2", "container[1]/?/?/container[@accessiblename>'kulaklık Modelleri, Fiyatları']/element[1]/element[1]/element/element[@accessiblerole='None']/element[2]/?/?/link[@accessiblename='  Sepetim 2']", "link[@accessiblename='  Sepetim 2']", 30000, null, "41b96af7-caa0-469f-a40f-ad6d028f7187");
                _sepetim2ueruenInfo = new RepoItemInfo(this, "Sepetim2UEruen", "container[1]/?/?/container[@accessiblename='Sepetim - Trendyol']/element[1]/element[3]/element[@accessiblerole='None']/element[1]/text[@accessiblename='Sepetim (2 Ürün)']", "text[@accessiblename='Sepetim (2 Ürün)']", 30000, null, "69a9fbb8-9f52-498e-bc0f-81b21ef3986a");
                _none8Info = new RepoItemInfo(this, "None8", "container[1]/?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element/element[@accessiblerole='None']/element[2]/element/element[1]", "container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[2]/element[@accessiblerole='None']/element[1]", 30000, null, "f0f73b0b-fd70-4908-bb4d-cf18f2593120");
                _none9Info = new RepoItemInfo(this, "None9", "container[1]/?/?/container[@accessiblename='']/element[1]/element[1]/element/element[@accessiblerole='None']/element[2]/element[@accessiblerole='None']/element[@accessiblerole='None']", "container[@accessiblename='']/element[1]/element[1]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[2]/element[@accessiblerole='None']/element[@accessiblerole='None']", 30000, null, "9ddba48a-30d6-4271-887f-4f5d384c4961");
                _aradığınızueruenkategoriveyamarkayı1Info = new RepoItemInfo(this, "AradığınızUeruenKategoriVeyaMarkayı1", "container[1]/?/?/container[@accessiblename>'Kadın Butikleri, Yeni Sezon']/element[1]/element[1]/element/element[@accessiblerole='None']/element[1]/element[@accessiblerole='None']/element[2]/text[@accessiblename>'Aradığınız ürün, kategori']", "text[@accessiblename>'Aradığınız ürün, kategori']", 30000, null, "c35c421e-8385-42ab-b545-f079f74127fa");
                _sepeteekle1Info = new RepoItemInfo(this, "SepeteEkle1", ".//container[@accessiblename>'kulaklık Modelleri, Fiyatları']/element[1]/element[3]/element[6]/button[@accessiblename>'Sepete Ekle Sepete Eklend']/?/?/text[@accessiblename='Sepete Ekle']", "text[@accessiblename='Sepete Ekle']", 30000, null, "d6fd05c3-cbad-4ec2-80e1-06b99d11ec2b");
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", "container[1]/?/?/container[@accessiblename>'kulaklık Modelleri, Fiyatları']/element[1]/element[1]//link[@accessiblename='  Sepetim 2']/element[3]/text[@accessiblename='Sepetim']", "text[@accessiblename='Sepetim']", 30000, null, "aef5e144-7d79-4d00-a83b-3e77becc4e38");
                _sepetim2ueruen1Info = new RepoItemInfo(this, "Sepetim2UEruen1", "container[1]/?/?/container[@accessiblename='Sepetim - Trendyol']//text[@accessiblename='Sepetim (2 Ürün)']", "text[@accessiblename='Sepetim (2 Ürün)']", 30000, null, "e87ae0b9-8b75-4e15-a3fc-d7bdd7fd533c");
                _text2Info = new RepoItemInfo(this, "Text2", "container[1]/?/?/container[@accessiblename='Sepetim - Trendyol']/element[1]/element[3]/element[@accessiblerole='None']/text[2]", "container[@accessiblename='Sepetim - Trendyol']/element[1]/element[3]/element[@accessiblerole='None']/text[2]", 30000, null, "f0823bd9-0fb1-4dba-bb37-8f3c0a3138ed");
                _sometextInfo = new RepoItemInfo(this, "SomeText", "container[1]/?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element/element[@accessiblerole='None']/element[2]/element/element[1]/?/?/text[@accessiblename='']", "text[@accessiblename='']", 30000, null, "503efaad-2650-48a2-9366-8cf8e42f9eb8");
                _kulaklıkkategoriInfo = new RepoItemInfo(this, "KulaklıkKategori", "container[1]/?/?/container[@accessiblename>'Kadın Butikleri, Yeni Sezon']/element[1]/element[1]/element/element[@accessiblerole='None']/element[1]/?/?/link[@accessiblename='Kulaklık Kategori']", "link[@accessiblename='Kulaklık Kategori']", 30000, null, "409795b1-1f50-4c06-aafd-1473ac8b07cf");
                _sepeteeklesepeteeklendiInfo = new RepoItemInfo(this, "SepeteEkleSepeteEklendi", ".//container[@accessiblename='Tüm Ürünler - Trendyol']/element[1]/element[3]/element[6]/button[@accessiblename>'Sepete Ekle Sepete Eklend']", "button[@accessiblename>'Sepete Ekle Sepete Eklend']", 30000, null, "56b4bfea-31b6-497d-a682-e602d446334e");
                _sepetim1Info = new RepoItemInfo(this, "Sepetim1", "container[1]/?/?/container[@accessiblename='Tüm Ürünler - Trendyol']/element[1]/element[1]//link[@accessiblename='  Sepetim 1']/element[3]/text[@accessiblename='Sepetim']", "text[@accessiblename='Sepetim']", 30000, null, "7c2e60b9-9ca6-4566-bba8-d75cef111745");
                _pushbuttonInfo = new RepoItemInfo(this, "PushButton", "container[1]/?/?/container[@accessiblename='Sepetim - Trendyol']/element[1]/element[3]/element[@accessiblerole='None']/button[2]", "container[@accessiblename='Sepetim - Trendyol']/element[1]/element[3]/element[@accessiblerole='None']/button[2]", 30000, null, "0806ad21-c08a-4b24-8bfe-85f3cdb11a07");
                _aradığınızueruenkategoriveyamarkayı2Info = new RepoItemInfo(this, "AradığınızUeruenKategoriVeyaMarkayı2", "container[1]/?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element/element[@accessiblerole='None']/element[1]//text[@accessiblename>'Aradığınız ürün, kategori']", "text[@accessiblename>'Aradığınız ürün, kategori']", 30000, null, "d18b5489-704e-41f9-8859-cc7c33c5943d");
                _none10Info = new RepoItemInfo(this, "None10", "container[1]/?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element/element[@accessiblerole='None']/element[1]/element[@accessiblerole='None']/element[2]/element[@accessiblerole='None']", "container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[1]/element[@accessiblerole='None']/element[2]/element[@accessiblerole='None']", 30000, null, "f6714897-c875-45a7-92d3-1cd8e662fd82");
                _none11Info = new RepoItemInfo(this, "None11", "container[1]/?/?/container[@accessiblename>'kulaklık Modelleri, Fiyatları']/element[1]/element[3]/element[7]", "container[@accessiblename>'kulaklık Modelleri, Fiyatları']/element[1]/element[3]/element[7]", 30000, null, "8e95b9a9-3bb1-40d3-8462-350d3e1c6396");
                _linkfavorilerimInfo = new RepoItemInfo(this, "LinkFavorilerim", "container[1]/?/?/container[@accessiblename>'kulaklık Modelleri, Fiyatları']/element[1]/element[1]/element/element[@accessiblerole='None']/element[2]/?/?/link[@accessiblename='  Favorilerim']", "link[@accessiblename='  Favorilerim']", 30000, null, "1b755fdd-003d-411e-9a7e-e6c3417bfc07");
                _favorilerlistenizhenuezboşInfo = new RepoItemInfo(this, "FavorilerListenizHenuezBoş", "container[1]/?/?/container[@accessiblename='Favoriler - Trendyol']/element[1]/element[3]/element[@accessiblerole='None']/element[7]/text[@accessiblename>'Favoriler Listeniz Henüz']", "text[@accessiblename>'Favoriler Listeniz Henüz']", 30000, null, "5aee6328-21ed-45ac-b389-8df2224410ce");
                _cıkışyapInfo = new RepoItemInfo(this, "CıkışYap", "container[1]/?/?/container[@accessiblename='Siparişlerim - Trendyol']/element[1]/element[1]//link[@accessiblename=' Çıkış Yap']/text[@accessiblename='Çıkış Yap']", "text[@accessiblename='Çıkış Yap']", 30000, null, "ddfeb62f-090d-480a-8f3b-60f83bbf2411");
                _none12Info = new RepoItemInfo(this, "None12", "container[1]/?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element/element[@accessiblerole='None']/element[2]/element[@accessiblerole='None']/element[1]/element[3]", "container[@accessiblename>'En Trend Ürünler Türkiye''nin']/element[1]/element[1]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[2]/element[@accessiblerole='None']/element[1]/element[3]", 30000, null, "39e030f0-cc0b-4114-b11a-1cf9c92eafec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fff7e9de-1425-4e9b-8009-1f4ab08189b1")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fff7e9de-1425-4e9b-8009-1f4ab08189b1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EPosta item.
            /// </summary>
            [RepositoryItem("fb6d563c-056a-46f8-b546-3007e01fc71a")]
            public virtual Ranorex.Text EPosta
            {
                get
                {
                    return _epostaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EPosta item info.
            /// </summary>
            [RepositoryItemInfo("fb6d563c-056a-46f8-b546-3007e01fc71a")]
            public virtual RepoItemInfo EPostaInfo
            {
                get
                {
                    return _epostaInfo;
                }
            }

            /// <summary>
            /// The Şifre item.
            /// </summary>
            [RepositoryItem("cb34a144-8ae5-47c5-ba3e-d06bd9e5421d")]
            public virtual Ranorex.Text Şifre
            {
                get
                {
                    return _şifreInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Şifre item info.
            /// </summary>
            [RepositoryItemInfo("cb34a144-8ae5-47c5-ba3e-d06bd9e5421d")]
            public virtual RepoItemInfo ŞifreInfo
            {
                get
                {
                    return _şifreInfo;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("162014f1-c456-4759-9200-d3df20733114")]
            public virtual Ranorex.Unknown None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("162014f1-c456-4759-9200-d3df20733114")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("16635d52-2ab8-41b8-8263-c2ccf419cc71")]
            public virtual Ranorex.Button UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("16635d52-2ab8-41b8-8263-c2ccf419cc71")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The None1 item.
            /// </summary>
            [RepositoryItem("fa3be3e8-7c21-4a56-9cfa-6eec45b9add5")]
            public virtual Ranorex.Unknown None1
            {
                get
                {
                    return _none1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None1 item info.
            /// </summary>
            [RepositoryItemInfo("fa3be3e8-7c21-4a56-9cfa-6eec45b9add5")]
            public virtual RepoItemInfo None1Info
            {
                get
                {
                    return _none1Info;
                }
            }

            /// <summary>
            /// The ComboBox item.
            /// </summary>
            [RepositoryItem("7a1d5176-8a97-41e0-8157-a235275bd7f2")]
            public virtual Ranorex.ComboBox ComboBox
            {
                get
                {
                    return _comboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox item info.
            /// </summary>
            [RepositoryItemInfo("7a1d5176-8a97-41e0-8157-a235275bd7f2")]
            public virtual RepoItemInfo ComboBoxInfo
            {
                get
                {
                    return _comboboxInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("7fb7e098-0622-4a4b-b0f3-6a9447920062")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("7fb7e098-0622-4a4b-b0f3-6a9447920062")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("91090ad5-2bc5-4dc4-a5b9-f30b03fe470e")]
            public virtual Ranorex.Text GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("91090ad5-2bc5-4dc4-a5b9-f30b03fe470e")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The UEYEOL1 item.
            /// </summary>
            [RepositoryItem("25c5d3ef-6c04-45a1-bef2-d553c1523130")]
            public virtual Ranorex.Button UEYEOL1
            {
                get
                {
                    return _ueyeol1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UEYEOL1 item info.
            /// </summary>
            [RepositoryItemInfo("25c5d3ef-6c04-45a1-bef2-d553c1523130")]
            public virtual RepoItemInfo UEYEOL1Info
            {
                get
                {
                    return _ueyeol1Info;
                }
            }

            /// <summary>
            /// The ComboBox1 item.
            /// </summary>
            [RepositoryItem("6bfb9698-eeab-43c9-b88b-6318c424e96f")]
            public virtual Ranorex.ComboBox ComboBox1
            {
                get
                {
                    return _combobox1Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox1 item info.
            /// </summary>
            [RepositoryItemInfo("6bfb9698-eeab-43c9-b88b-6318c424e96f")]
            public virtual RepoItemInfo ComboBox1Info
            {
                get
                {
                    return _combobox1Info;
                }
            }

            /// <summary>
            /// The None2 item.
            /// </summary>
            [RepositoryItem("260b5e68-f14c-4bb6-ab0b-f76fd035e4f0")]
            public virtual Ranorex.Unknown None2
            {
                get
                {
                    return _none2Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None2 item info.
            /// </summary>
            [RepositoryItemInfo("260b5e68-f14c-4bb6-ab0b-f76fd035e4f0")]
            public virtual RepoItemInfo None2Info
            {
                get
                {
                    return _none2Info;
                }
            }

            /// <summary>
            /// The None3 item.
            /// </summary>
            [RepositoryItem("534547dc-2426-4aae-a932-560ebda0b847")]
            public virtual Ranorex.Unknown None3
            {
                get
                {
                    return _none3Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None3 item info.
            /// </summary>
            [RepositoryItemInfo("534547dc-2426-4aae-a932-560ebda0b847")]
            public virtual RepoItemInfo None3Info
            {
                get
                {
                    return _none3Info;
                }
            }

            /// <summary>
            /// The None4 item.
            /// </summary>
            [RepositoryItem("66570af6-2cd4-43f8-bc25-4c9424e052dc")]
            public virtual Ranorex.Unknown None4
            {
                get
                {
                    return _none4Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None4 item info.
            /// </summary>
            [RepositoryItemInfo("66570af6-2cd4-43f8-bc25-4c9424e052dc")]
            public virtual RepoItemInfo None4Info
            {
                get
                {
                    return _none4Info;
                }
            }

            /// <summary>
            /// The UEYEOL2 item.
            /// </summary>
            [RepositoryItem("44cec552-b412-4b8e-a8be-5559ecfedd0b")]
            public virtual Ranorex.Button UEYEOL2
            {
                get
                {
                    return _ueyeol2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UEYEOL2 item info.
            /// </summary>
            [RepositoryItemInfo("44cec552-b412-4b8e-a8be-5559ecfedd0b")]
            public virtual RepoItemInfo UEYEOL2Info
            {
                get
                {
                    return _ueyeol2Info;
                }
            }

            /// <summary>
            /// The TextE180504008AtatudTauEduTr item.
            /// </summary>
            [RepositoryItem("8e2a2e88-f857-4fd5-8e7a-ccd5487587c4")]
            public virtual Ranorex.Text TextE180504008AtatudTauEduTr
            {
                get
                {
                    return _texte180504008atatudtauedutrInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextE180504008AtatudTauEduTr item info.
            /// </summary>
            [RepositoryItemInfo("8e2a2e88-f857-4fd5-8e7a-ccd5487587c4")]
            public virtual RepoItemInfo TextE180504008AtatudTauEduTrInfo
            {
                get
                {
                    return _texte180504008atatudtauedutrInfo;
                }
            }

            /// <summary>
            /// The None5 item.
            /// </summary>
            [RepositoryItem("9f0b9477-5519-467f-9db3-b1127cbb11de")]
            public virtual Ranorex.Unknown None5
            {
                get
                {
                    return _none5Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None5 item info.
            /// </summary>
            [RepositoryItemInfo("9f0b9477-5519-467f-9db3-b1127cbb11de")]
            public virtual RepoItemInfo None5Info
            {
                get
                {
                    return _none5Info;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("0a134ab0-6a03-4cc9-ad39-a65813bdcdb0")]
            public virtual Ranorex.Text Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("0a134ab0-6a03-4cc9-ad39-a65813bdcdb0")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The LuetfenGecerliBirEmailAdresiGiriniz item.
            /// </summary>
            [RepositoryItem("5130c23e-674b-4f8c-900c-b6e70ab6f05f")]
            public virtual Ranorex.Text LuetfenGecerliBirEmailAdresiGiriniz
            {
                get
                {
                    return _luetfengecerlibiremailadresigirinizInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LuetfenGecerliBirEmailAdresiGiriniz item info.
            /// </summary>
            [RepositoryItemInfo("5130c23e-674b-4f8c-900c-b6e70ab6f05f")]
            public virtual RepoItemInfo LuetfenGecerliBirEmailAdresiGirinizInfo
            {
                get
                {
                    return _luetfengecerlibiremailadresigirinizInfo;
                }
            }

            /// <summary>
            /// The TextE180504008AtstudTauEduTr item.
            /// </summary>
            [RepositoryItem("2dfcf164-ac26-429f-8b64-a250c08c0b2c")]
            public virtual Ranorex.Text TextE180504008AtstudTauEduTr
            {
                get
                {
                    return _texte180504008atstudtauedutrInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextE180504008AtstudTauEduTr item info.
            /// </summary>
            [RepositoryItemInfo("2dfcf164-ac26-429f-8b64-a250c08c0b2c")]
            public virtual RepoItemInfo TextE180504008AtstudTauEduTrInfo
            {
                get
                {
                    return _texte180504008atstudtauedutrInfo;
                }
            }

            /// <summary>
            /// The GİRİŞYAP item.
            /// </summary>
            [RepositoryItem("3c3019ef-f5d4-4394-a610-381907977ca5")]
            public virtual Ranorex.Button GİRİŞYAP
            {
                get
                {
                    return _gİrİşyapInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GİRİŞYAP item info.
            /// </summary>
            [RepositoryItemInfo("3c3019ef-f5d4-4394-a610-381907977ca5")]
            public virtual RepoItemInfo GİRİŞYAPInfo
            {
                get
                {
                    return _gİrİşyapInfo;
                }
            }

            /// <summary>
            /// The AradığınızUeruenKategoriVeyaMarkayı item.
            /// </summary>
            [RepositoryItem("15ff16fd-5706-41b2-813d-922b2939b735")]
            public virtual Ranorex.Text AradığınızUeruenKategoriVeyaMarkayı
            {
                get
                {
                    return _aradığınızueruenkategoriveyamarkayıInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AradığınızUeruenKategoriVeyaMarkayı item info.
            /// </summary>
            [RepositoryItemInfo("15ff16fd-5706-41b2-813d-922b2939b735")]
            public virtual RepoItemInfo AradığınızUeruenKategoriVeyaMarkayıInfo
            {
                get
                {
                    return _aradığınızueruenkategoriveyamarkayıInfo;
                }
            }

            /// <summary>
            /// The None6 item.
            /// </summary>
            [RepositoryItem("085fa678-5b08-4e6b-a2ba-c061530a2c11")]
            public virtual Ranorex.Unknown None6
            {
                get
                {
                    return _none6Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None6 item info.
            /// </summary>
            [RepositoryItemInfo("085fa678-5b08-4e6b-a2ba-c061530a2c11")]
            public virtual RepoItemInfo None6Info
            {
                get
                {
                    return _none6Info;
                }
            }

            /// <summary>
            /// The None7 item.
            /// </summary>
            [RepositoryItem("f46e98cf-2457-4f18-bd4e-d16c560aebd1")]
            public virtual Ranorex.Unknown None7
            {
                get
                {
                    return _none7Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None7 item info.
            /// </summary>
            [RepositoryItemInfo("f46e98cf-2457-4f18-bd4e-d16c560aebd1")]
            public virtual RepoItemInfo None7Info
            {
                get
                {
                    return _none7Info;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("adc7d11e-3df4-4e74-b642-10d9cc800c08")]
            public virtual Ranorex.Text SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("adc7d11e-3df4-4e74-b642-10d9cc800c08")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The LinkSepetim2 item.
            /// </summary>
            [RepositoryItem("41b96af7-caa0-469f-a40f-ad6d028f7187")]
            public virtual Ranorex.Link LinkSepetim2
            {
                get
                {
                    return _linksepetim2Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkSepetim2 item info.
            /// </summary>
            [RepositoryItemInfo("41b96af7-caa0-469f-a40f-ad6d028f7187")]
            public virtual RepoItemInfo LinkSepetim2Info
            {
                get
                {
                    return _linksepetim2Info;
                }
            }

            /// <summary>
            /// The Sepetim2UEruen item.
            /// </summary>
            [RepositoryItem("69a9fbb8-9f52-498e-bc0f-81b21ef3986a")]
            public virtual Ranorex.Text Sepetim2UEruen
            {
                get
                {
                    return _sepetim2ueruenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Sepetim2UEruen item info.
            /// </summary>
            [RepositoryItemInfo("69a9fbb8-9f52-498e-bc0f-81b21ef3986a")]
            public virtual RepoItemInfo Sepetim2UEruenInfo
            {
                get
                {
                    return _sepetim2ueruenInfo;
                }
            }

            /// <summary>
            /// The None8 item.
            /// </summary>
            [RepositoryItem("f0f73b0b-fd70-4908-bb4d-cf18f2593120")]
            public virtual Ranorex.Unknown None8
            {
                get
                {
                    return _none8Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None8 item info.
            /// </summary>
            [RepositoryItemInfo("f0f73b0b-fd70-4908-bb4d-cf18f2593120")]
            public virtual RepoItemInfo None8Info
            {
                get
                {
                    return _none8Info;
                }
            }

            /// <summary>
            /// The None9 item.
            /// </summary>
            [RepositoryItem("9ddba48a-30d6-4271-887f-4f5d384c4961")]
            public virtual Ranorex.Unknown None9
            {
                get
                {
                    return _none9Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None9 item info.
            /// </summary>
            [RepositoryItemInfo("9ddba48a-30d6-4271-887f-4f5d384c4961")]
            public virtual RepoItemInfo None9Info
            {
                get
                {
                    return _none9Info;
                }
            }

            /// <summary>
            /// The AradığınızUeruenKategoriVeyaMarkayı1 item.
            /// </summary>
            [RepositoryItem("c35c421e-8385-42ab-b545-f079f74127fa")]
            public virtual Ranorex.Text AradığınızUeruenKategoriVeyaMarkayı1
            {
                get
                {
                    return _aradığınızueruenkategoriveyamarkayı1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AradığınızUeruenKategoriVeyaMarkayı1 item info.
            /// </summary>
            [RepositoryItemInfo("c35c421e-8385-42ab-b545-f079f74127fa")]
            public virtual RepoItemInfo AradığınızUeruenKategoriVeyaMarkayı1Info
            {
                get
                {
                    return _aradığınızueruenkategoriveyamarkayı1Info;
                }
            }

            /// <summary>
            /// The SepeteEkle1 item.
            /// </summary>
            [RepositoryItem("d6fd05c3-cbad-4ec2-80e1-06b99d11ec2b")]
            public virtual Ranorex.Text SepeteEkle1
            {
                get
                {
                    return _sepeteekle1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle1 item info.
            /// </summary>
            [RepositoryItemInfo("d6fd05c3-cbad-4ec2-80e1-06b99d11ec2b")]
            public virtual RepoItemInfo SepeteEkle1Info
            {
                get
                {
                    return _sepeteekle1Info;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("aef5e144-7d79-4d00-a83b-3e77becc4e38")]
            public virtual Ranorex.Text Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("aef5e144-7d79-4d00-a83b-3e77becc4e38")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The Sepetim2UEruen1 item.
            /// </summary>
            [RepositoryItem("e87ae0b9-8b75-4e15-a3fc-d7bdd7fd533c")]
            public virtual Ranorex.Text Sepetim2UEruen1
            {
                get
                {
                    return _sepetim2ueruen1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Sepetim2UEruen1 item info.
            /// </summary>
            [RepositoryItemInfo("e87ae0b9-8b75-4e15-a3fc-d7bdd7fd533c")]
            public virtual RepoItemInfo Sepetim2UEruen1Info
            {
                get
                {
                    return _sepetim2ueruen1Info;
                }
            }

            /// <summary>
            /// The Text2 item.
            /// </summary>
            [RepositoryItem("f0823bd9-0fb1-4dba-bb37-8f3c0a3138ed")]
            public virtual Ranorex.Text Text2
            {
                get
                {
                    return _text2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text2 item info.
            /// </summary>
            [RepositoryItemInfo("f0823bd9-0fb1-4dba-bb37-8f3c0a3138ed")]
            public virtual RepoItemInfo Text2Info
            {
                get
                {
                    return _text2Info;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("503efaad-2650-48a2-9366-8cf8e42f9eb8")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("503efaad-2650-48a2-9366-8cf8e42f9eb8")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The KulaklıkKategori item.
            /// </summary>
            [RepositoryItem("409795b1-1f50-4c06-aafd-1473ac8b07cf")]
            public virtual Ranorex.Link KulaklıkKategori
            {
                get
                {
                    return _kulaklıkkategoriInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The KulaklıkKategori item info.
            /// </summary>
            [RepositoryItemInfo("409795b1-1f50-4c06-aafd-1473ac8b07cf")]
            public virtual RepoItemInfo KulaklıkKategoriInfo
            {
                get
                {
                    return _kulaklıkkategoriInfo;
                }
            }

            /// <summary>
            /// The SepeteEkleSepeteEklendi item.
            /// </summary>
            [RepositoryItem("56b4bfea-31b6-497d-a682-e602d446334e")]
            public virtual Ranorex.Button SepeteEkleSepeteEklendi
            {
                get
                {
                    return _sepeteeklesepeteeklendiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SepeteEkleSepeteEklendi item info.
            /// </summary>
            [RepositoryItemInfo("56b4bfea-31b6-497d-a682-e602d446334e")]
            public virtual RepoItemInfo SepeteEkleSepeteEklendiInfo
            {
                get
                {
                    return _sepeteeklesepeteeklendiInfo;
                }
            }

            /// <summary>
            /// The Sepetim1 item.
            /// </summary>
            [RepositoryItem("7c2e60b9-9ca6-4566-bba8-d75cef111745")]
            public virtual Ranorex.Text Sepetim1
            {
                get
                {
                    return _sepetim1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Sepetim1 item info.
            /// </summary>
            [RepositoryItemInfo("7c2e60b9-9ca6-4566-bba8-d75cef111745")]
            public virtual RepoItemInfo Sepetim1Info
            {
                get
                {
                    return _sepetim1Info;
                }
            }

            /// <summary>
            /// The PushButton item.
            /// </summary>
            [RepositoryItem("0806ad21-c08a-4b24-8bfe-85f3cdb11a07")]
            public virtual Ranorex.Button PushButton
            {
                get
                {
                    return _pushbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PushButton item info.
            /// </summary>
            [RepositoryItemInfo("0806ad21-c08a-4b24-8bfe-85f3cdb11a07")]
            public virtual RepoItemInfo PushButtonInfo
            {
                get
                {
                    return _pushbuttonInfo;
                }
            }

            /// <summary>
            /// The AradığınızUeruenKategoriVeyaMarkayı2 item.
            /// </summary>
            [RepositoryItem("d18b5489-704e-41f9-8859-cc7c33c5943d")]
            public virtual Ranorex.Text AradığınızUeruenKategoriVeyaMarkayı2
            {
                get
                {
                    return _aradığınızueruenkategoriveyamarkayı2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AradığınızUeruenKategoriVeyaMarkayı2 item info.
            /// </summary>
            [RepositoryItemInfo("d18b5489-704e-41f9-8859-cc7c33c5943d")]
            public virtual RepoItemInfo AradığınızUeruenKategoriVeyaMarkayı2Info
            {
                get
                {
                    return _aradığınızueruenkategoriveyamarkayı2Info;
                }
            }

            /// <summary>
            /// The None10 item.
            /// </summary>
            [RepositoryItem("f6714897-c875-45a7-92d3-1cd8e662fd82")]
            public virtual Ranorex.Unknown None10
            {
                get
                {
                    return _none10Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None10 item info.
            /// </summary>
            [RepositoryItemInfo("f6714897-c875-45a7-92d3-1cd8e662fd82")]
            public virtual RepoItemInfo None10Info
            {
                get
                {
                    return _none10Info;
                }
            }

            /// <summary>
            /// The None11 item.
            /// </summary>
            [RepositoryItem("8e95b9a9-3bb1-40d3-8462-350d3e1c6396")]
            public virtual Ranorex.Unknown None11
            {
                get
                {
                    return _none11Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None11 item info.
            /// </summary>
            [RepositoryItemInfo("8e95b9a9-3bb1-40d3-8462-350d3e1c6396")]
            public virtual RepoItemInfo None11Info
            {
                get
                {
                    return _none11Info;
                }
            }

            /// <summary>
            /// The LinkFavorilerim item.
            /// </summary>
            [RepositoryItem("1b755fdd-003d-411e-9a7e-e6c3417bfc07")]
            public virtual Ranorex.Link LinkFavorilerim
            {
                get
                {
                    return _linkfavorilerimInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkFavorilerim item info.
            /// </summary>
            [RepositoryItemInfo("1b755fdd-003d-411e-9a7e-e6c3417bfc07")]
            public virtual RepoItemInfo LinkFavorilerimInfo
            {
                get
                {
                    return _linkfavorilerimInfo;
                }
            }

            /// <summary>
            /// The FavorilerListenizHenuezBoş item.
            /// </summary>
            [RepositoryItem("5aee6328-21ed-45ac-b389-8df2224410ce")]
            public virtual Ranorex.Text FavorilerListenizHenuezBoş
            {
                get
                {
                    return _favorilerlistenizhenuezboşInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FavorilerListenizHenuezBoş item info.
            /// </summary>
            [RepositoryItemInfo("5aee6328-21ed-45ac-b389-8df2224410ce")]
            public virtual RepoItemInfo FavorilerListenizHenuezBoşInfo
            {
                get
                {
                    return _favorilerlistenizhenuezboşInfo;
                }
            }

            /// <summary>
            /// The CıkışYap item.
            /// </summary>
            [RepositoryItem("ddfeb62f-090d-480a-8f3b-60f83bbf2411")]
            public virtual Ranorex.Text CıkışYap
            {
                get
                {
                    return _cıkışyapInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CıkışYap item info.
            /// </summary>
            [RepositoryItemInfo("ddfeb62f-090d-480a-8f3b-60f83bbf2411")]
            public virtual RepoItemInfo CıkışYapInfo
            {
                get
                {
                    return _cıkışyapInfo;
                }
            }

            /// <summary>
            /// The None12 item.
            /// </summary>
            [RepositoryItem("39e030f0-cc0b-4114-b11a-1cf9c92eafec")]
            public virtual Ranorex.Unknown None12
            {
                get
                {
                    return _none12Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None12 item info.
            /// </summary>
            [RepositoryItemInfo("39e030f0-cc0b-4114-b11a-1cf9c92eafec")]
            public virtual RepoItemInfo None12Info
            {
                get
                {
                    return _none12Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
